name: Run APK Download Script

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install unzip
      run: sudo apt-get install unzip -y


    - name: Install pup
      run: |
        wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
        unzip pup.zip
        chmod +x pup
        sudo mv pup /usr/local/bin/
      working-directory: .  # Set the working directory to the root directory

    - name: Grant execute permissions to script
      run: chmod +x script.sh
      working-directory: .  # Set the working directory to the root directory

    - name: Run APK Download Script
      run: |
        ./script.sh "https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-12-57-0-55-release/"  # Update with your APK link
      working-directory: .  # Set the working directory to the root directory
