name: Run APK Download Script

on:
  push:
    branches:
      - main  # Update with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Install unzip
      run: sudo apt-get install unzip -y


    - name: Install pup
      run: |
        wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
        unzip pup.zip
        chmod +x pup
        sudo mv pup /usr/local/bin/
      working-directory: .  # Set the working directory to the root directory

    - name: Grant execute permissions to script
      run: chmod +x script.sh
      working-directory: .  # Set the working directory to the root directory

    - name: Run APK Download Script
      run: |
        ./script.sh
      working-directory: .  # Set the working directory to the root directory
